name: CI workflow
on: 
    push
jobs:
    ci-pipeline:
        name: ci-pipeline
        runs-on: ubuntu-latest
        steps:
            - name: checkout step
              uses: actions/checkout@v4
            - name: list files
              run: ls -lrth 