name: My first workflow
on: [push]
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Bismillah message
        run: echo "Bismillah hirrahman nirraheem, starting my first workflow"
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: list files
        run: ls -la
      - name: Read file
        run: cat README.md